version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx_dev
    volumes:
      - ./public:/usr/share/nginx/public
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/distance_log
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: