version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    volumes:
      - ./public:/usr/share/nginx/public
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/distance_log
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
